name: Project setup workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Run-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Packages
        run: |
          cd ./frontend
          npm ci
        shell: bash
      - name: Running linting 
        run: |
          cd ./frontend
          npm run lint
        shell: bash

  building-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Packages
        run: |
          cd ./frontend
          npm ci
        shell: bash
      - name: Building 
        run: |
          cd ./frontend
          npm run build
        shell: bash